name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build  -t ing2isimm2024/sysnetadmin:app  .
    - name: Deploy to Render
      uses: gh-actions-workflows/deploy-docker-render@v1.1
      with:
        deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
        image-url: ing2isimm2024/sysnetadmin:app
        render-api-key: ${{ secrets.RENDER_API_KEY }}
        wait-for-deployment: true
